### ISSUE TITLE
[BUG] Mini player disappears when minimized

### ISSUE THREAD

**Issue by Danalytics-dan** [deeffest/Youtube-Music-Desktop-Player#2]
### Description
if you minimise the miniplayer it just becomes invisible but keeps on playing music forever. The only way to stop it is task manager system tray doesn't work.

### Steps to Reproduce
1. Step 1 enable system tray plugin
2. Step 2 turn on miniplayer
3. Step 3 minimize the miniplayer
4. it disappears

### Expected Behavior
What did you expect to happen? it should minimize and be re-openable by pressing the icon at the bottom

### Actual Behavior
What actually happened? that miniplayer can't be re-opened

### Screenshots or Logs
N/A

### Environment
- **Operating System**: (e.g. Windows 10 22h2)
- **Version of the App**: (e.g. 1.23.4)
- **Additional information**: (e.g., Is this a fresh installation or an upgrade?)

### Additional Information
Please provide any other information that might be helpful in resolving the issue. For example, if the problem only happens in certain conditions or with specific settings.

**Comment by deeffest** [comment]
Ideally, in Windows 10/11, when you hide the mini-player, it minimizes to the bottom left corner, from where you can either expand it to its previous state or close it (closing it will open the main window and the tray icon (if enabled)).

![изображение](https://github.com/user-attachments/assets/0947c766-b7c0-4ac6-a77b-f5edca43de28)

You didn't specify the version of Windows and the version of the application you're using when the error occurs, so I can't tell you anything more right now.

**Comment by Danalytics-dan** [comment]
Wow I'm blind yeah it's there. I didn't see it cause my game was on fullscreen so it went under it.

Sorry for wasting your time
